branch-defaults:
  master:
    environment: soulpurpose-dev
  mdl:
    environment: null
    group_suffix: null
global:
  application_name: soulpurpose
  default_ec2_keyname: aws-eb
  default_platform: Docker 1.7.1
  default_region: us-west-2
  profile: eb-cli
  sc: git
